# Generated by Django 4.1.7 on 2023-04-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mercaderias', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenproductos')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mercaderias.productos')),
            ],
        ),
    ]
