# Generated by Django 4.1.7 on 2023-04-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercaderias', '0005_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenproductos'),
        ),
    ]
